name: enviroment

channels:
  - conda-forge
  - scipp
  - nodefaults
  - mantid

dependencies:
  - ess=0.9
  - jupyterlab
  - jupyterlab_widgets
  - pythreejs
  - scipy
  - ipympl
  - mantid
  - pip:
      - sasdata
      - sasmodels
      - bumps