name: enviroment

channels:
  - conda-forge
  - scipp
  - nodefaults
  - mantid

dependencies:
  - ess
  - astropy
  - matplotlib
  - tifffile
  - jupyterlab
  - jupyterlab_widgets
  - pythreejs
  - scipy
  - ipympl
  - mantid
  - python-graphviz
  - jupyter_contrib_nbextensions
  - pip:
      - sasdata
      - sasmodels