# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 dmsc-nightly contributors (https://github.com/dmsc-nightly)

name: environment

channels:
  - conda-forge
  - scipp
  - mantid
  - nodefaults

dependencies:
  - ess>0.9
  - jupyterlab
  - mantid
  - pytest
  - pip:
      - sasdata
      - sasmodels
      - bumps
