# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 dmsc-nightly contributors (https://github.com/dmsc-nightly)

name: environment

channels:
  - conda-forge
  - scipp
  - mantid
  - nodefaults

dependencies:
  - ess>0.9
  - ipympl=0.9.2
  - jupyterlab=3.5.2
  - mantid=6.5.0
  - pip=22.3.1
  - pytest=7.2.1
  - python=3.8
  - pythreejs=2.4.1
  - pip:
      - sasdata
      - sasmodels
      - bumps==0.9.0
