name: nightly

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  simple_workflow:
    name: Setups enviroment for scipp and sasview
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    steps:

      - uses: actions/checkout@v3

      - name: Setup conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: 0.23.0
          environment-file: environment.yml
          cache-env: false
          extra-specs: python=3.9

      - run: python sans2d_to_I_of_Q.py # runs scipp script and generates test.h5 file

      - run: python sasmodels_fit.py #runs sasview/sasmodels script by reading in test.h5 and fitting some model (fit is shit!)
