name: nightly

on:
  [push, pull_request]

jobs:
  simple_workflow:
    name: Setups enviroment for scipp and sasview
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    steps:

      - uses: actions/checkout@v3

      - name: Setup conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: 0.23.0
          environment-file: environment.yml
          cache-env: false
          extra-specs: python=3.9

      - name: Fetch scipp/ess repository
        run: git clone --depth=50 --branch=main https://github.com/scipp/ess.git

      - name: Converting notebook to python script
        run: |
          cd ess/docs/instruments/loki
          jupyter nbconvert --to script sans2d_to_I_of_Q.ipynb

      - name: Data reduction with scipp
        run: |
          python ess/docs/instruments/loki/sans2d_to_I_of_Q.py # runs scipp script and generates test.h5 file

      -name: SasView fitting
        run: |
          python sasmodels_fit.py #runs sasview/sasmodels script by reading in test.h5 and fitting some model (fit is shit!)
